"""PDF renderer: validated report dict -> printable dossier exhibit.

reportlab platypus layout (Helvetica, gridded tables): title page (campaign,
target, date), executive summary, scorecard table, findings table
(ID/Technique/Severity/Status) and per-pack remediation bullets. Raises
``ValueError`` when the report dict is missing any required section, so a
half-built report can never be rendered. Table cells are plain strings (no
markup parsing); ``Paragraph`` text is XML-escaped."""
import os
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (PageBreak, Paragraph, SimpleDocTemplate,
                                Spacer, Table, TableStyle)

__all__ = ["render_pdf", "REQUIRED_KEYS"]

REQUIRED_KEYS = ("meta", "executive", "scorecard", "findings", "remediation")

_TITLE = ParagraphStyle("RFTitle", fontName="Helvetica-Bold", fontSize=22,
                        leading=27, textColor=colors.HexColor("#1a1a1a"))
_META = ParagraphStyle("RFMeta", fontName="Helvetica", fontSize=11,
                       leading=16, textColor=colors.HexColor("#444444"))
_H1 = ParagraphStyle("RFH1", fontName="Helvetica-Bold", fontSize=14,
                     leading=18, spaceBefore=10 * mm, spaceAfter=3 * mm,
                     textColor=colors.HexColor("#1a1a1a"))
_BODY = ParagraphStyle("RFBody", fontName="Helvetica", fontSize=10,
                       leading=14, spaceAfter=2 * mm)
_SMALL = ParagraphStyle("RFSmall", fontName="Helvetica-Oblique", fontSize=8,
                        leading=11, textColor=colors.HexColor("#777777"))


def _table(rows: list[list[str]], widths: list[float],
           bold_last: bool = False) -> Table:
    cmds = [
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8e8e8")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#9a9a9a")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#f6f6f6")]),
    ]
    if bold_last:
        cmds.append(("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"))
    t = Table(rows, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle(cmds))
    return t


def render_pdf(report: dict, out_path: str) -> str:
    """Render a validated report dict to ``out_path``; returns ``out_path``."""
    missing = [k for k in REQUIRED_KEYS if k not in report]
    if missing:
        raise ValueError(
            f"report dict missing required key(s): {', '.join(missing)}")

    parent = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(parent, exist_ok=True)

    meta = report["meta"]
    story = [
        Spacer(1, 45 * mm),
        Paragraph("AI-RedForge Security Assessment", _TITLE),
        Spacer(1, 10 * mm),
        Paragraph(f"Campaign: {escape(str(meta.get('campaign_id', '')))}", _META),
        Paragraph(f"Target: {escape(str(meta.get('target', '')))}", _META),
        Paragraph(f"Generated: {escape(str(meta.get('generated', '')))}", _META),
        PageBreak(),
        Paragraph("Executive Summary", _H1),
        Paragraph(escape(str(report["executive"])), _BODY),
    ]

    sc = report["scorecard"]
    score_rows = [["Dimension", "Weighted"]]
    for dim, weighted in (sc.get("contributions") or {}).items():
        score_rows.append([str(dim), str(weighted)])
    score_rows.append(["Total", f"{sc.get('total', '')} ({sc.get('band', '')})"])
    story += [Paragraph("Scorecard", _H1),
              _table(score_rows, [115 * mm, 45 * mm], bold_last=True)]

    finding_rows = [["ID", "Technique", "Severity", "Status"]]
    for f in report["findings"]:
        finding_rows.append([str(f.get("id", "")), str(f.get("technique_id", "")),
                             str(f.get("severity", "")), str(f.get("status", ""))])
    story.append(Paragraph("Findings", _H1))
    if len(finding_rows) > 1:
        story.append(_table(finding_rows, [28 * mm, 32 * mm, 30 * mm, 76 * mm]))
    else:
        story.append(Paragraph("No findings recorded.", _BODY))

    story.append(Paragraph("Remediation", _H1))
    for pack, text in (report.get("remediation") or {}).items():
        story.append(Paragraph(
            f"&bull; <b>{escape(str(pack))}:</b> {escape(str(text))}", _BODY))

    story += [
        Spacer(1, 8 * mm),
        Paragraph("Automatically generated by AI-RedForge. Supporting "
                  "evidence for the EU AI Act Article 15 dossier; human "
                  "review required before external release.", _SMALL),
    ]

    doc = SimpleDocTemplate(
        out_path, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title="AI-RedForge Security Assessment")
    doc.build(story)
    return out_path
